import type { Metadata } from "next";
import { Toaster } from "react-hot-toast"; // ★追加
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        {/* ここに配置することで、アプリ内のどこからでも通知を出せます */}
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
